#!/bin/bash
set -e

echo "=== GradTure — Railway + Vercel Deployment Checklist ==="
echo ""

echo "Prerequisites:"
echo "  [ ] GitHub repository connected to Railway (backend)"
echo "  [ ] GitHub repository connected to Vercel (frontend)"
echo "  [ ] PostgreSQL database provisioned on Railway (or external)"
echo "  [ ] Domain gradture.ai DNS configured (point to Vercel)"
echo "  [ ] Domain api.gradture.ai DNS configured (point to Railway)"
echo "  [ ] Environment variables configured in Railway and Vercel"
echo ""

echo "=== Railway Backend Setup ==="
echo ""
echo "1. Create new Railway project or connect existing repo"
echo "2. Set root directory to: backend/"
echo "3. Railway will auto-detect Dockerfile and build"
echo ""
echo "--- AI Configuration (provider-agnostic) ---"
echo "Set these in Railway: Variables tab > New Variable"
echo ""
echo "Primary provider:"
echo "  AI_PROVIDER=gemini"
echo "  GEMINI_API_KEY=<your-real-gemini-key>"
echo "  GEMINI_MODEL=gemini-2.0-flash"
echo ""
echo "Optional fallback provider:"
echo "  AI_FALLBACK_PROVIDER="
echo ""
echo "Optional alternative providers:"
echo "  OPENAI_API_KEY="
echo "  OPENAI_MODEL=gpt-4o-mini"
echo "  OPENAI_BASE_URL="
echo ""
echo "  GROQ_API_KEY="
echo "  GROQ_MODEL=llama-3.3-70b-versatile"
echo ""
echo "  OLLAMA_BASE_URL=http://localhost:11434"
echo "  OLLAMA_MODEL=llama3.2"
echo ""
echo "Note: Only fill the API key for the provider(s) you actually use."
echo "      Leave unused provider keys empty to avoid accidental usage."
echo ""
echo "Required Railway environment variables:"
echo "  DATABASE_URL=<postgres-connection-string>"
echo "  JWT_SECRET=<secure-64-char-hex>"
echo "  JWT_EXPIRES_IN=7d"
echo "  CORS_ORIGIN=https://gradture.ai,https://www.gradture.ai,https://admin.gradture.ai"
echo "  FRONTEND_URL=https://gradture.ai"
echo "  AI_PROVIDER=gemini"
echo "  GEMINI_API_KEY=<google-gemini-api-key>"
echo "  GEMINI_MODEL=gemini-2.0-flash"
echo "  # Optional fallback provider:"
echo "  AI_FALLBACK_PROVIDER="
echo "  # Optional OpenAI:"
echo "  OPENAI_API_KEY="
echo "  OPENAI_MODEL=gpt-4o-mini"
echo "  # Optional Groq:"
echo "  GROQ_API_KEY="
echo "  GROQ_MODEL=llama-3.3-70b-versatile"
echo "  # Optional Ollama:"
echo "  OLLAMA_BASE_URL=http://localhost:11434"
echo "  OLLAMA_MODEL=llama3.2"
echo "  RESEND_API_KEY=<resend-api-key>"
echo "  SMTP_FROM=GradTure <noreply@gradture.ai>"
echo "  REDIS_URL=<redis-connection-string>  # optional"
echo "  SENTRY_DSN=<sentry-dsn>  # optional"
echo "  SENTRY_ENVIRONMENT=production"
echo "  SENTRY_RELEASE=gradture@1.0.0"
echo "  LOG_LEVEL=info"
echo "  ADMIN_SETUP_SECRET=<secure-random-hex>"
echo "  STORAGE_PROVIDER=r2  # or s3, local"
echo "  R2_ACCOUNT_ID=<r2-account-id>"
echo "  R2_BUCKET=gradture-uploads"
echo "  R2_ENDPOINT=https://<r2-account-id>.r2.cloudflarestorage.com"
echo "  R2_ACCESS_KEY=<r2-access-key>"
echo "  R2_SECRET_KEY=<r2-secret-key>"
echo ""
echo "4. Deploy backend to Railway"
echo "   - Railway will run: docker build && docker deploy"
echo "   - Entrypoint runs: prisma migrate deploy && node dist/main.js"
echo "   - Health check: GET /health"
echo ""

echo "=== Vercel Frontend Setup ==="
echo ""
echo "1. Import project from GitHub to Vercel"
echo "2. Set root directory to: frontend/"
echo "3. Vercel will auto-detect Vite and build"
echo ""
echo "Required Vercel environment variables (in Project Settings > Environment Variables):"
echo "  VITE_API_URL=https://api.gradture.ai/api/v1"
echo "  VITE_SENTRY_DSN=<sentry-dsn>  # optional"
echo "  VITE_APP_VERSION=1.0.0"
echo ""
echo "4. Deploy frontend to Vercel"
echo "   - Build command: npm run build (auto-detected)"
echo "   - Output directory: dist (auto-detected)"
echo "   - SPA routing handled by vercel.json"
echo ""

echo "=== Database Migrations ==="
echo ""
echo "Migrations run automatically on Railway backend startup via docker-entrypoint.sh"
echo "To run manually:"
echo "  cd backend && npx prisma migrate deploy"
echo ""

echo "=== DNS Configuration ==="
echo ""
echo "Configure these DNS records at your domain registrar:"
echo "  gradture.ai        -> Vercel (A record or CNAME)"
echo "  www.gradture.ai    -> Vercel (CNAME)"
echo "  api.gradture.ai    -> Railway (CNAME or A record)"
echo "  admin.gradture.ai  -> Vercel (same as gradture.ai) or Railway"
echo ""

echo "=== Post-Deployment Verification ==="
echo ""
echo "Backend (Railway):"
echo "  curl https://api.gradture.ai/health"
echo "  curl https://api.gradture.ai/api/v1/jobs"
echo ""
echo "Frontend (Vercel):"
echo "  curl https://gradture.ai"
echo "  curl https://gradture.ai/jobs"
echo ""
echo "Full flow test:"
echo "  1. Visit https://gradture.ai"
echo "  2. Register as talent and employer"
echo "  3. Create job, apply, send message"
echo "  4. Verify notifications appear"
echo ""

echo "=== Rollback ==="
echo ""
echo "Railway: Use Railway dashboard to rollback to previous deployment"
echo "Vercel: Use Vercel dashboard to promote previous preview"
echo ""

echo "=== Checklist Complete ==="
