#!/bin/bash
set -e

echo "=== GradHire AI — Deployment Checklist ==="
echo ""

echo "Prerequisites:"
echo "  [ ] Railway CLI installed and logged in (railway login)"
echo "  [ ] Vercel CLI installed and logged in (vercel login)"
echo "  [ ] Railway projects created: gradhire-backend, gradhire-ai-service"
echo "  [ ] Vercel project created: gradhire-frontend"
echo "  [ ] PostgreSQL database provisioned (Railway or external)"
echo "  [ ] Environment variables configured in Railway/Vercel"
echo ""

echo "Step 1: Build and push Docker images (optional — CI/CD handles this on push to main)"
echo "  cd backend && docker build -t gradhire/backend:latest ."
echo "  cd ai-service && docker build -t gradhire/ai-service:latest ."
echo "  cd frontend && docker build -t gradhire/frontend:latest ."
echo ""

echo "Step 2: Deploy backend to Railway"
echo "  cd backend"
echo "  railway init gradhire-backend"
echo "  railway up"
echo ""

echo "Step 3: Deploy AI service to Railway"
echo "  cd ai-service"
echo "  railway init gradhire-ai-service"
echo "  railway up"
echo ""

echo "Step 4: Run PostgreSQL migrations on production database"
echo "  export DATABASE_URL=postgresql://user:pass@host:5432/gradhire"
echo "  cd backend"
echo "  npx prisma migrate deploy"
echo ""

echo "Step 5: Deploy frontend to Vercel"
echo "  cd frontend"
echo "  vercel --prod"
echo ""

echo "Step 6: Configure production environment variables"
echo "  Backend (Railway):"
echo "    DATABASE_URL=<production-postgres-url>"
echo "    JWT_SECRET=<secure-secret-32+ chars>"
echo "    AI_SERVICE_URL=<railway-ai-service-url>"
echo "    SMTP_HOST=smtp.sendgrid.net"
echo "    SMTP_PORT=587"
echo "    SMTP_USER=apikey"
echo "    SMTP_PASS=<sendgrid-api-key>"
echo "    SMTP_FROM=GradHire AI <noreply@yourdomain.com>"
echo "    CORS_ORIGIN=https://your-frontend-app.vercel.app"
echo "    FRONTEND_URL=https://your-frontend-app.vercel.app"
echo ""
echo "  AI Service (Railway):"
echo "    OPENAI_API_KEY=<your-openai-key>"
echo ""
echo "  Frontend (Vercel):"
echo "    VITE_API_URL=https://your-backend-url.com/api/v1"
echo ""

echo "Step 7: Verify production health checks"
echo "  curl https://your-backend-url.com/health"
echo "  curl https://your-ai-service-url.com/health"
echo "  curl https://your-frontend-app.vercel.app"
echo ""

echo "Step 8: Update vercel.json with real URLs"
echo "  Replace placeholder URLs in frontend/vercel.json with actual production URLs"
echo ""

echo "=== Checklist Complete ==="
