import type { LucideProps } from 'lucide-react';
import {
  LayoutDashboard,
  FileText,
  Briefcase,
  Bookmark,
  User,
  Settings,
  Mail,
  Bell,
  BarChart3,
  Users,
  Building2,
  ShieldCheck,
  Code2,
  Home,
  Search,
  Filter,
  Plus,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  Menu,
  X,
  Check,
  Sun,
  Moon,
  GraduationCap,
  Download,
  Upload,
  ExternalLink,
  Link2,
  Copy,
  RefreshCw,
  Loader2,
  FileBarChart,
  Brain,
  Database,
  Webhook,
  MessageSquare,
  Server,
  Star,
  Heart,
  Trash2,
  Eye,
  Lightbulb,
  Lock,
} from 'lucide-react';

type IconName = 'dashboard' | 'applications' | 'jobs' | 'saved' | 'profile' | 'settings' | 'messages' | 'notifications' | 'analytics' | 'interviews' | 'company' | 'users' | 'audit' | 'developer' | 'home' | 'search' | 'filter' | 'plus' | 'arrow-right' | 'arrow-left' | 'arrow-up' | 'arrow-down' | 'chevron-right' | 'chevron-left' | 'menu' | 'close' | 'check' | 'x' | 'mail' | 'bell' | 'star' | 'heart' | 'trash' | 'edit' | 'eye' | 'download' | 'upload' | 'external' | 'link' | 'copy' | 'refresh' | 'loader' | 'sun' | 'moon' | 'logo' | 'resume' | 'reports' | 'ai' | 'database' | 'api' | 'email' | 'cms' | 'feature' | 'backup' | 'security';

type IconProps = {
  name: IconName;
  size?: number;
  className?: string;
  'aria-hidden'?: boolean;
};

const COMPONENT_MAP: Record<IconName, React.FC<LucideProps>> = {
  logo: GraduationCap,
  dashboard: LayoutDashboard,
  applications: FileText,
  jobs: Briefcase,
  saved: Bookmark,
  profile: User,
  settings: Settings,
  messages: MessageSquare,
  notifications: Bell,
  analytics: BarChart3,
  interviews: Users,
  company: Building2,
  users: Users,
  audit: ShieldCheck,
  developer: Code2,
  home: Home,
  search: Search,
  filter: Filter,
  plus: Plus,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  menu: Menu,
  close: X,
  check: Check,
  x: X,
  mail: Mail,
  bell: Bell,
  star: Star,
  heart: Heart,
  trash: Trash2,
  edit: Eye,
  eye: Eye,
  download: Download,
  upload: Upload,
  external: ExternalLink,
  link: Link2,
  copy: Copy,
  refresh: RefreshCw,
  loader: Loader2,
  sun: Sun,
  moon: Moon,
  resume: FileText,
  reports: FileBarChart,
  ai: Brain,
  database: Database,
  api: Webhook,
  email: Mail,
  cms: Server,
  feature: Lightbulb,
  backup: Download,
  security: Lock,
};

export const Icon = ({ name, size = 20, className = '', 'aria-hidden': ariaHidden = true }: IconProps) => {
  const LucideIcon = COMPONENT_MAP[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} className={className} aria-hidden={ariaHidden} />;
};
